### ISSUE TITLE
[Question] Can I use cernbox URLs.

### ISSUE THREAD

**Issue by chibiegg** [aperloff/vivado-docker#4]
I want to merge the your great works to the original repository.

Now I'm working on rewriting the CERN-specific readme for general purpose.

Is it okay to leave the cernbox URL in the Dockerfile? Or should it be changed to use other means?

**Comment by aperloff** [comment]
You should change the URL to some other method for obtaining the tarballs. The cernbox URLs are not generally accessible to the public and they do expire.

**Comment by chibiegg** [comment]
Thanks!
I will change to use an other method and then merge.
